### PR TITLE
Top Bar PFP

### PR DESCRIPTION
**Pull request by ProTaxEvader**
Gets rid of the user icon next to your name in the menu bar (the one with home, profile, etc.) to be more accurate to 2016

### CODE REVIEW

**Comment by ProTaxEvader** [comment]
@anthony1x6000 ?

**Comment by anthony1x6000** [comment]
mb - it would better the faithfulness of the style to roblox in 2016, but I don't want to take away the functionality of the site. 
Preferrably, I would like to process this change as an optional feature.

**Comment by ProTaxEvader** [comment]
> mb - it would better the faithfulness of the style to roblox in 2016, but I don't want to take away the functionality of the site. Preferrably, I would like to process this change as an optional feature.

Yea feel free to do that, I don't mind you changing things. I tried to add this is as an option using "@var checkbox" but it didn't work out for me (im a css noob).

**Comment by anthony1x6000** [comment]
i looked into some documentation I found [here](https://github.com/openstyles/stylus/wiki/Writing-UserCSS#var) and tried the @ var and advanced tags but i could not get them to work.
Theres probably something conflicting within the style that is preventing the expected functionality.

I'm gonna have to dedicate some time trying to figure it out because the userstyle has gotten really messy and unorganized over the years I've been updating it - I started as a css noob too maintaining this style in 2019 so there's a lot of redundant rules scattered throughout the style 😔

**Comment by ProTaxEvader** [comment]
Either way if you cant figure it out dont worry about it, someone could find a fix and contribute and if not then people could always just paste my css at the bottom. Also I usually don't contribute to projects but I found that your userstyle was the only accurate non-broken and complete 2016 theme so for that I give props. 

Also you should check out making this guy's themes compatible because they are 1:1 with 2016:
https://uso.kkx.one/browse/styles?search=%401185261

**Comment by anthony1x6000** [comment]
I see mostly public domain licenses by them so I might paste in what they created already. Thanks, it'll def save a lot of work

**Comment by anthony1x6000** [comment]
kk found the thing messing with variable functionality and fixed it in a [recent commit](https://github.com/anthony1x6000/ROBLOX2016stylus/commit/46ae9b7c2bec96bf646cd9d3498c114f23617293)

**Pull request merged**
